version: "3.9"
services:
  frontend:
    build: .
    ports:
      - 3000:3000
    volumes:
      # binding basically everything
      - ./docs:/code/app/docs
      - ./public:/code/app/public
      - ./src:/code/app/src
    command: yarn dev:start
